### ISSUE TITLE
Update to 6.5

### ISSUE THREAD

**Issue by Tim-VL** [myparcelnl/shopware6#31]
Hi,

When can we expect the update to 6.5? Current version does not work...

We are now forced to use other shippers...

Thanks!

**Comment by Tim-VL** [comment]
Any updates on this matter?

**Comment by Tim-VL** [comment]
Hello?

Any updates on the 6.5 (out now for some months)

Thanks for a update.

**Comment by joerivanveen** [comment]
@Tim-VL we have just released 2.2.0 which is fully compatible with Shopware 6.5
