### ISSUE TITLE
Compatibility with V6.4.*

### ISSUE THREAD

**Issue by studiovlist** [myparcelnl/shopware6#4]
Hi,

I've installed this module on the pre-latest version of shopware at this moment (6.4.1.2) but it looks like the plugin isn't compatible with this version. I've have tested it on the default Shopware theme. 

There are many issues now because I have the feeling I can't access the plugin properly. So I think the main issue to fix is the following:

**In the release note is explained:** "Activate PostNL as a shipping method via Myparcel->Shipping methods and clicking the three dots. Choose the desired settings in the following menu and activate the shipping method." This menu item is not available. From 6.3 to 6.4 the way of accessing plugin settings and options are changed, maybe it has something to do with this?

**Comment by Mitchell-MyParcel** [comment]
@studiovlist: I can confirm that we have tested the plugin up to v6.3.5.4. Our main priority right now is getting the plugin in the store, but I will check with our dev partner what needs to be done to get the plugin running on the latest version. I will place an update in this thread once I know more.

I also see that we have not included the supported versions in our github entry so there was know way for you to know this. Our apologies for that, we will adjust this asap.

**Comment by studiovlist** [comment]
@Mitchell-MyParcel are there any updates regarding the plugin?

**Comment by Mitchell-MyParcel** [comment]
@studiovlist: You can install the new version via the store (which has v6.4 support) or wait until we publish the latest version on github tomorrow.

Store link:
https://store.shopware.com/mypa903869754442f/myparcel.html

**Comment by studiovlist** [comment]
@Mitchell-MyParcel thanks for the update. Going to install the plugin and test it out. When I find issues I will share them.
