### ISSUE TITLE
Type error in DeliveryCalculatorDecorator

### ISSUE THREAD

**Issue by NvdBrand** [myparcelnl/shopware6#68]
After the plugin is installed (version 2.3.0), I tried to add a product to the cart but receive the following error (also see screenshot)

Clearing cache didn't help.

MyPa\Shopware\Core\Checkout\Cart\Delivery\DeliveryCalculatorDecorator::__construct(): Argument #3 ($taxDetector) must be of type Shopware\Core\Checkout\Cart\Tax\TaxDetector, LenzPlatformVatIdValidation\Core\Checkout\Cart\Tax\TaxDetector given, called in /var/www/html/var/cache/dev_h1f818f124bb79c90d70e5e2aab850d52/ContainerOsxeSAX/Shopware_Core_KernelDevDebugContainer.php on line 31269

<img width="1042" alt="image" src="https://github.com/myparcelnl/shopware6/assets/171135095/7386f33b-8213-45c5-853d-a9349108f533">

**Comment by joerivanveen** [comment]
The fix is planned for june 18th 2024, we will reference this thread in the PR.
